---

- name: add repository GPG key for Yarn
  become: yes
  apt_key:
    url: https://dl.yarnpkg.com/debian/pubkey.gpg
  when: ansible_os_family == "Debian"

- name: add repository for Yarn
  become: yes
  apt_repository:
    repo: deb https://dl.yarnpkg.com/debian/ stable main
  when: ansible_os_family == "Debian"
  register: yarn_repo

- name: update apt cache
  become: yes
  apt:
    update_cache: yes
  when: yarn_repo.changed

- name: install Yarn
  become: yes
  package:
    pkg: yarn
    state: latest
  with_together:
    - nodejs
    - yarn
