---

# https://github.com/pyenv/pyenv
- name: check if pyenv is already installed
  become: yes
  become_user: "{{ username }}"
  stat:
    path: "~/.pyenv"
  register: pyenv_install

- name: download pyenv installer
  become: yes
  become_user: "{{ username }}"
  get_url:
    url: https://raw.githubusercontent.com/pyenv/pyenv-installer/master/bin/pyenv-installer
    dest: /tmp/pyenv-installer
  when: not pyenv_install.stat.exists

- name: execute pyenv installer
  become: yes
  become_user: "{{ username }}"
  command: bash /tmp/pyenv-installer
  when: not pyenv_install.stat.exists

- name: install python versions with pyenv
  become: yes
  become_user: "{{ username }}"
  command: ~/.pyenv/bin/pyenv install {{ item }}
  args:
    creates: "~/.pyenv/versions/{{ item }}"
  with_items: "{{ pyenv.versions }}"
