---

- name: setup global known_hosts
  become: true
  known_hosts:
    path: /etc/ssh/known_hosts
    name: "{{ item }}"
    key: "{{ lookup('pipe', 'ssh-keyscan -T 10 -H -t rsa ' + item) }}"
    state: present
  with_items:
    - github.com
    - gitlab.com

- name: add custom CA
  become: true
  copy:
    src: "{{ item }}"
    dest: "/usr/local/share/ca-certificates/{{ item }}"
    # Validate the CA will not expire in less than 4 months
    validate: openssl x509 -noout -checkend 10520000 -enddate -in %s
  loop: "{{ certificates_extra }}"
  when: certificates_extra is defined
  notify: update-ca-certificates

- name: check grub customization
  lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT=".*{{ grub_parameter }}'
    state: absent
  check_mode: true
  register: grub_cmdline_check
  changed_when: false
  when: grub_parameter is defined

- name: insert grub customization
  become: true
  lineinfile:
    backrefs: true
    path: /etc/default/grub
    regexp: '^(GRUB_CMDLINE_LINUX_DEFAULT=".*)"$'
    line: '\1 {{ grub_parameter }}"'
  when: grub_parameter is defined and grub_cmdline_check.found == 0
  notify: update grub

#- name: install custom fonts
# sudo fc-cache -fv
