---

- name: fetch packages information
  package_facts:
    manager: auto

# Known bug: https://github.com/ansible/ansible/issues/29363
- name: setup global known_hosts
  become: yes
  known_hosts:
    path=/etc/ssh/known_hosts
    name="{{ item }}"
    key="{{ lookup('pipe', 'ssh-keyscan -T 10 -H -t rsa ' + item) }}"
    state=present
  with_items:
    - github.com
    - bitbucket.org
    - gitlab.com
