---

- name: add repository GPG key for Atlassian SDK
  become: yes
  apt_key:
    url: https://packages.atlassian.com/api/gpg/key/public
  tags: atlassian

- name: add reposiroty for Atlassian SDK
  become: yes
  apt_repository:
    repo: deb https://packages.atlassian.com/debian/atlassian-sdk-deb/ stable contrib
  tags: atlassian

- name: install Atlassian SDK
  become: yes
  apt:
    pkg: atlassian-plugin-sdk
  tags: atlassian
