---

- name: install common packages
  become: true
  package:
    pkg: "{{ item }}"
  with_together:
    - apt-transport-https
    - chromium-browser
    - cups
    - cups-client
    - curl
    - dnsutils
    - git
    - git-lfs
    - gpg
    - gpg-agent
    - htop
    - man
    - openssh-client
    - openssh-server
    - openssl
    - pass
    - pass-extension-otp
    - silversearcher-ag
    - sudo
    - vim
    - wget
    - whois

- name: install extra packages
  become: true
  package:
    pkg: "{{ packages_extra | join(',') }}"
  when: packages_extra
