---

- name: install common packages
  become: true
  package:
    pkg: "{{ item }}"
  with_together:
    - ack
    - apt-transport-https
    - byobu
    - cups
    - cups-client
    - curl
    - dnsutils
    - git
    - git-lfs
    - gpg
    - gpg-agent
    - htop
    - iftop
    - inputplug
    - ipcalc
    - keychain
    - man
    - mtr
    - net-tools
    - ocrmypdf
    - tesseract-ocr-fra
    - oathtool
    - openssh-client
    - openssh-server
    - openssl
    - pass
    - pass-extension-otp
    - pigz
    - pssh
    - pwgen
    - qpdf
    - qrencode
    - sudo
    - tmate
    - vim
    - wget
    - whois
    - xz-utils
    - yubikey-manager
    - zbar-tools

- name: install Debian package
  become: true
  package:
    pkg: "{{ item }}"
  with_together:
    - task-english
  when: ansible_distribution == "Debian"
