---

- name: Dist upgrade
  hosts: [laptop]
  become: true
  roles:
    - common/upgrade
    - locales

- name: Configure laptop
  hosts: [laptop]
  become: true
  roles:
    - packages/apt-debian
#    - packages/dropbox
    - packages/sublime
    - packages/yarn
  vars:
    debian_release: testing