---

- name: Gathering packages facts
  hosts: [all]
  tasks:
    - name: fetch packages information
      package_facts:
        manager: auto
  tags:
    - system
    - user

- name: Configure system
  hosts: [all]
  roles:
    - locales
    - packages/apt-debian
    - common/configuration
    - common/upgrade
    - common/hardware
    - packages/sshd
    - user/setup
    - packages/sudo
    - packages/common
    - packages/desktop
    - packages/firefox
    - packages/dropbox
    - packages/sublime
    - packages/python
    - packages/pipsi
    - packages/virtualization
    - packages/dbeaver
    - packages/development/toolbox
    - packages/development/java
    - packages/development/docker
    - packages/signal
    - packages/audible
    - packages/calibre
    - user/config
    - user/zsh
    - packages/intellij
  vars:
    locales:
      - fr_CH.UTF-8
      - en_US.UTF-8
      - en_CA.UTF-8
    debian_releases:
      - name: testing
        priority: 800
        security: yes
      - name: unstable
        priority: -1
        security: no
    user_preferences: yes
