---

- name: Gathering packages facts
  hosts: [all]
  tasks:
    - name: fetch packages information
      package_facts:
        manager: auto
  tags:
    - system
    - always

- name: Configure system
  hosts: [all]
  roles:
    - role: locales
      tags: locales

    - role: packages/apt
      tags: apt
      when: ansible_os_family == "Debian"

#    - role: common/configuration
#      tags: configuration

    - role: common/upgrade
      tags: upgrade, never

#    - role: common/hardware
#      tags: hardware, system

    - role: common/hibernate
      tags: hibernate

# Not yet
#    - role: packages/sshd
#      tags: ssh

    - role: user/setup
      tags: user

    - role: user/config
      tags: user, config

    - role: packages/sudo
      tags: sudo

    - role: packages/common
      tags: common

    - role: packages/desktop
      tags: desktop

    - role: packages/go
      tags: dev

    - role: packages/hashicorp
      tags: hashicorp

    - role: packages/hashicorp/tfenv
      tags: tfenv
      when: not private_node

    - role: packages/hashicorp/hashienv
      tags: hashienv

    - role: packages/hashicorp
      tags: hashicorp

    - role: packages/python
      tags: python

    - role: packages/pyenv
      tags: pyenv

    - role: packages/pipx
      tags: pipx

#    - role: packages/virtualization
#      tags: virtualization

    - role: packages/development/toolbox
      tags: dev, toolbox

    - role: packages/gh
      tags: gh

    # Pycharm
    - role: packages/development/jetbrains
      tags: dev

    - role: packages/development/postman
      tags: dev

    #- role: packages/development/java
    #  tags: dev, java

    - role: packages/development/docker
      tags: dev, docker

    - role: packages/development/nodejs
      tags: dev, javascript, nodejs
      when: nodejs is defined

    - role: packages/development/yarn
      tags: dev, javascript, yarn
      when: not private_node

#    - role: work
#      tags: work
#      when: not private_node

    - role: packages/awsvault
      tags: awsvault
      when: not private_node

    - role: packages/firefox
      tags: firefox

    - role: packages/drawio
      tags: drawio

    - role: packages/signal
      tags: signal

    - role: user/zsh
      tags: user, zsh

    - role: user/finalchecks
      tags: user

  tags:
    - packages
