---

- name: Dist upgrade
  hosts: [laptop]
  become: true
  roles:
    - common/upgrade
    - locales

- name: Configure laptop
  hosts: [laptop]
  roles:
    - packages/apt-debian
    - packages/firefox
#    - packages/dropbox
    - packages/sublime
    - packages/yarn
  vars:
    debian_releases:
      - name: testing
        priority: 800
        security: yes
      - name: unstable
        priority: -1
        security: no