---

- name: Gathering packages facts
  hosts: [all]
  tasks:
    - name: fetch packages information
      package_facts:
        manager: auto
    - name: set platform type
      set_fact:
        private_node : "{{ ansible_nodename in ('play', 'x1') }}"
    - name: set work facts
      set_fact:
        username: mbrothie
      when: not private_node
    - name: set private facts
      set_fact:
        username: marco
      when: private_node
  tags:
    - system
    - user
    - always

- name: Configure system
  hosts: [all]
  roles:
    - role: locales
      tags: locales
    - role: packages/apt
      tags: apt
      when: ansible_os_family == "Debian"
    - role: common/configuration
      tags: configuration
    - role: common/upgrade
      tags: upgrade, never
    - role: common/hardware
      tags: hardware, system
    - role: packages/sshd
      tags: ssh
    - role: user/setup
      tags: user
    - role: packages/sudo
      tags: sudo
    - role: packages/common
      tags: common
    - role: packages/desktop
      tags: desktop
    - role: packages/firefox
      tags: firefox
      #- role: packages/dropbox
      #  tags: dropbox
      #- role: packages/sublime
      #  tags: sublime
    - role: packages/python
      tags: python
    - role: packages/pipx
      tags: pipx
    - role: packages/virtualization
      tags: virtualization
    #- role: packages/helm
    #  tags: helm, k8s
    #  when: not private_node
    #- role: packages/dbeaver
    #  tags: dbeaver
    - role: packages/drawio
      tags: drawio
    - role: packages/development/toolbox
      tags: dev, toolbox
    #- role: packages/development/java
    #  tags: dev, java

    - role: packages/development/docker
      tags: dev, docker

    #- role: packages/minikube
    #  tags: minikube

    - role: packages/signal
      tags: signal

    - role: packages/brave
      tags: brave

    #- role: packages/audible
    #  tags: audible

    - role: user/config
      tags: user, config

    - role: user/zsh
      tags: user, zsh

    - role: packages/kdrive
      tags: kdrive
      when: private_node

    - role: packages/lunii
      tags: lunii
      when: private_node

    - role: packages/calibre
      tags: calibre
      when: private_node

    #- role: packages/intellij
    #  tags: intellij
    #- role: packages/mattermost-desktop
    #  tags: mattermost
    #  when: not private_node
    #- role: packages/joplin
    #  tags: joplin
  tags:
    - packages
  vars:
    locales:
      - fr_CH.UTF-8
      - en_US.UTF-8
      - en_CA.UTF-8
    debian_releases:
      - name: testing
        priority: 800
        security: yes
    user_preferences: yes
