---

- name: Gathering packages facts
  hosts: [laptop]
  tasks:
    - name: fetch packages information
      package_facts:
        manager: auto
  tags:
    - system
    - user
    - exoscale

- name: Configure system
  hosts: [laptop]
  roles:
    - locales
    - packages/apt-debian
    - common/configuration
    - common/upgrade
    - common/hardware
    - packages/sshd
    - packages/sudo
    - packages/common
    - packages/desktop
    - packages/firefox
    - packages/dropbox
    - packages/sublime
    - packages/python
    - packages/virtualization
    - packages/dbeaver
    - packages/development/toolbox
    - packages/development/java
    - packages/development/docker
    - packages/development/javascript
    - user/setup
  vars:
    locales:
      - fr_CH.UTF-8
      - en_US.UTF-8
      - en_CA.UTF-8
    debian_releases:
      - name: testing
        priority: 800
        security: yes
      - name: unstable
        priority: -1
        security: no
  tags:
    - system

- name: Configure user environment
  hosts: [laptop]
  roles:
    - user/config
    - user-packages/zsh
    - user-packages/desktop
    - user-packages/intellij
    - user-packages/pyenv
    - user-packages/pipsi
    - user-packages/dropbox
    - user-packages/audible
  tags:
    - user

- name: Configure user environment for Exoscale
  hosts: [laptop]
  roles:
    - exoscale/setup
    - exoscale/projects
  vars_files:
    - roles/exoscale/common.yml
  vars:
    ansible_user: marco
  tags:
    - exoscale
