---

- name: Dist upgrade
  hosts: [laptop]
  become: true
  roles:
    - common/upgrade
    - locales
  vars:
    locales:
      - fr_CH.UTF-8
      - en_US.UTF-8
      - en_CA.UTF-8

- name: Configure laptop
  hosts: [laptop]
  # become: true
  roles:
    - packages/apt-debian
    - packages/common
    - packages/desktop
    - packages/firefox
#    - packages/dropbox
    - packages/sublime
    - packages/python
    - packages/virtualization
    - packages/development/toolbox
    - packages/development/java
    - packages/development/docker
    - packages/development/javascript
  vars:
    debian_releases:
      - name: testing
        priority: 800
        security: yes
      - name: unstable
        priority: -1
        security: no

- name: Configure laptop for {{ username }}
  hosts: [laptop]
  roles:
    - user/setup
    - user-packages/intellij
    - user-packages/pyenv
    - user-packages/pipsi
  tags:
    - user
  vars:
    username: marco
    packages_directory: "~/soft"
    pyenv:
      versions:
        - 2.7.15
        - 3.5.6
        - 3.6.6
      default: 3.6.6
    pipsi_tools:
      - name: cs
      - name: flake8
        extra: flake8-import-order flake8-bugbear
      - name: pip-tools
      - name: sphinx
        extra: sphinx-rtd-theme recommonmark
      - name: runstatus-cli
      - name: black
      - name: ansible
        extra: passlib
