---

- name: Dist upgrade
  hosts: [laptop]
  become: true
  roles:
    - common/upgrade
    - locales

- name: Configure laptop
  hosts: [laptop]
  # become: true
  roles:
    - packages/apt-debian
    - packages/common
    - packages/desktop
    - packages/firefox
#    - packages/dropbox
    - packages/sublime
    - packages/python
    - packages/virtualization
    - packages/development/toolbox
    - packages/development/java
    - packages/development/docker
    - packages/development/yarn
  vars:
    debian_releases:
      - name: testing
        priority: 800
        security: yes
      - name: unstable
        priority: -1
        security: no