---

- name: check home diretory for {{ username }}
  stat:
    path: "/home/{{ username }}"
    get_checksum: no
  register: user_home

- name: prompting for {{ username }} password if needed
  pause:
    prompt: "Give a password for {{ username }}"
    echo: no
  when: not user_home.stat.exists
  register: user_password

- name: set user {{ username }} password
  become: yes
  user:
    name: "{{ username }}"
    state: present
    password: "{{ user_password.user_input |password_hash('sha512') }}"
    update_password: on_create
  when: not user_home.stat.exists

- name: verify user configuration
  become: yes
  user:
    name: "{{ username }}"
    shell: "/usr/bin/zsh"
    state: present
    append: yes
    groups:
      - audio
      - bluetooth
      - cdrom
      - dip
      - floppy
      - plugdev
      - netdev
      - sudo
      - video
      # - scanner

- name: change home permissions for {{ username }}
  become: yes
  become_user: "{{ username }}"
  file:
    path: "~/"
    state: directory
    mode: 0750

- name: create directory for ansible remote_tmp to skip warning
  become: yes
  become_user: "{{ username }}"
  file:
    path: "~/.ansible/tmp"
    state: directory
    mode: 0750

- name: add authorized ssh keys
  become: yes
  become_user: "{{ username }}"
  authorized_key:
    key: https://github.com/marcaurele.keys
    comment: "github user key for marcaurele"
    state: present
    user: "{{ username }}"

- name: create directories
  become: yes
  become_user: "{{ username }}"
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ packages_directory }}"
    - "{{ code_directory }}"
