---

- name: check home directory for {{ username }}
  become: yes
  stat:
    path: "/home/{{ username }}"
    get_checksum: no
  register: user_home

- name: prompting for {{ username }} password if needed
  pause:
    prompt: "Give a password for {{ username }}"
    echo: no
  when: not user_home.stat.exists
  register: user_password

- name: set user {{ username }} password
  become: yes
  user:
    name: "{{ username }}"
    state: present
    password: "{{ user_password.user_input |password_hash('sha512') }}"
    update_password: on_create
  when: not user_home.stat.exists

- name: verify user configuration
  become: yes
  user:
    name: "{{ username }}"
    state: present
    append: yes
    groups:
      - audio
      - bluetooth
      - cdrom
      - dip
      - floppy
      - plugdev
      - netdev
      - video
      # - scanner
