---

- name: add repository GPG key for Sublime
  become: yes
  apt_key:
    url: https://download.sublimetext.com/sublimehq-pub.gpg
  when: ansible_os_family == "Debian"

- name: add repository for Sublime
  become: yes
  apt_repository:
    repo: deb https://download.sublimetext.com/ apt/stable/
  when: ansible_os_family == "Debian"

- name: install Sublime
  become: yes
  apt:
    pkg: sublime-text
    state: latest
