---

- name: install development toolbox packages
  become: yes
  package:
    pkg: "{{ item }}"
  with_together:
    - automake
    - build-essential
    - cmake
    - git
    - golang
    - gpg
    - gpg-agent
    - jq
    - libbz2-dev
    - libreadline-dev
    - libsqlite3-dev
    - libssl-dev
    - libtool
    - make
    - postgresql-client
