---

- name: install development toolbox packages
  become: yes
  package:
    pkg: "{{ item }}"
    state: latest
  with_together:
    - automake
    - build-essential
    - cmake
    - default-mysql-client
    - git
    - gpg
    - gpg-agent
    - jq
    - kafkacat
    - libbz2-dev
    - libmariadbclient-dev-compat
    - libncurses5-dev
    - libncursesw5-dev
    - libqt5sql5-mysql
    - libqt5sql5-psql
    - libqt5sql5-sqlite
    - libreadline-dev
    - libsqlite3-dev
    - libssl-dev
    - libtool
    - llvm
    - make
    - qtbase5-dev
    - qttools5-dev-tools
    - weechat
    - zlib1g-dev
