---

- name: install i3 packages
  become: yes
  package:
    pkg: "{{ item }}"
    state: latest
  with_together:
    - i3
    - i3blocks
    - i3status
    - i3lock
    - fonts-powerline
    - powerline

- name: configure a i3lock on sleep
  become: yes
  template:
    src: i3lock-sleep.service.j2
    dest: /etc/systemd/system/i3lock-sleep@.service

- name: create i3 config directory
  become: yes
  become_user: "{{ username }}"
  file:
    path: "~/.config/i3"
    state: directory
  when: ansible_facts.packages['i3'] is defined

- name: configure i3
  become: yes
  become_user: "{{ username }}"
  template:
    src: i3-config.j2
    dest: ~/.config/i3/config
  when: ansible_facts.packages['i3'] is defined

- name: configure i3 status
  become: yes
  become_user: "{{ username }}"
  template:
    src: i3-status.conf.j2
    dest: ~/.i3status.conf
  when: ansible_facts.packages['i3status'] is defined

- name: configure i3blocks
  become: yes
  become_user: "{{ username }}"
  template:
    src: i3-blocks.conf.j2
    dest: ~/.i3blocks.conf

- name: enable i3lock on sleep service for {{ username }}
  become: yes
  systemd:
    enabled: yes
    name: "i3lock-sleep@{{ username }}.service"
    daemon_reload: yes
  when: ansible_facts.packages['i3lock'] is defined
