---

- name: install desktop
  become: yes
  package:
    pkg: "{{ item }}"
    state: latest
  with_together:
    - blueman
    - brightnessctl
    - calibre
    - chromium
    - dictionaries-common
    - evolution
    - fonts-symbola
    - gimp
    - gocryptfs
    - hunspell-en-us
    - hunspell-fr-modern
    - inkscape
    - libreoffice
    - network-manager
    - network-manager-gnome
    - pavucontrol
    - pulseaudio
    - remmina
    - rdesktop
    - telegram-desktop
    - treesheets
    - vlc
    - suckless-tools
    - syncevolution
    - task-desktop
    - task-gnome-desktop
    - x11-xkb-utils
    - xclip
    - xfce4-terminal
    - xinput
    - xsettingsd

- name: import i3 tasks
  import_tasks: i3.yml
