---

- name: install desktop
  become: yes
  package:
    pkg: "{{ item }}"
    state: latest
  with_items:
    - blueman
    - brightnessctl
    - calibre
    - chromium
    - fonts-symbola
    - gimp
    - gocryptfs
    - inkscape
    - libreoffice
    - network-manager
    - network-manager-gnome
    - pavucontrol
    - pulseaudio
    - remmina
    - rdesktop
    - treesheets
    - vlc
    - suckless-tools
    - xfce4-terminal
    - xinput
    - xsettingsd

- name: install i3 packages
  become: yes
  package:
    pkg: "{{ item }}"
    state: latest
  with_items:
    - i3
    - i3status
    - i3lock
