---

- name: install desktop
  become: yes
  package:
    pkg: "{{ item }}"
    state: latest
  with_together:
    - blueman
    - brightnessctl
    - calibre
    - chromium
    - fonts-symbola
    - gimp
    - gocryptfs
    - inkscape
    - libreoffice
    - network-manager
    - network-manager-gnome
    - pavucontrol
    - pulseaudio
    - remmina
    - rdesktop
    - telegram-desktop
    - treesheets
    - vlc
    - suckless-tools
    - task-desktop
    - task-gnome-desktop
    - x11-xkb-utils
    - xfce4-terminal
    - xinput
    - xsettingsd

- name: install i3 packages
  become: yes
  package:
    pkg: "{{ item }}"
    state: latest
  with_together:
    - i3
    - i3status
    - i3lock
