---

- name: check drawio releases
  uri:
    url: https://api.github.com/repos/jgraph/drawio-desktop/releases
    return_content: yes
  register: releases
  tags: system

- name: install or upgrade draw.io desktop
  become: yes
  apt:
    deb: "https://github.com/jgraph/drawio-desktop/releases/download/{{ releases.json[0].tag_name }}/draw.io-amd64-{{ releases.json[0].name }}.deb"
    state: present
  when: ansible_facts.packages['draw.io'] is not defined or ansible_facts.packages['draw.io'][0].version != releases.json[0].name
  tags: system
