---

- name: check drawio releases
  uri:
    url: https://api.github.com/repos/jgraph/drawio-desktop/releases/latest
    return_content: yes
  register: releases
  tags: system

- name: debug releases
  debug:
    var: releases

- name: debug facts
  debug:
    var: ansible_facts.packages

- name: install or upgrade draw.io desktop
  become: yes
  apt:
    deb: "https://github.com/jgraph/drawio-desktop/releases/download/{{ releases.json.tag_name }}/draw.io-amd64-{{ releases.json.name }}.deb"
    state: present
  when: ansible_facts.packages['draw.io'] is not defined or ansible_facts.packages['draw.io'][0].version != releases.json.name
  tags: system
