---

- name: add repository GPG key for GitHub CLI
  become: yes
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: C99B11DEB97541F0

- name: add reposiroty for GitHub CLI
  become: yes
  apt_repository:
    repo: deb https://cli.github.com/packages {{ ansible_distribution_release }}  main

- name: install GitHub CLI
  become: yes
  apt:
    pkg:
      - gh
