---

- name: install weechat
  become: yes
  package:
    pkg: "{{ item }}"
  with_together:
    - weechat

- name: install python-nofity2 for weechat plugin
  become: yes
  apt:
    pkg: python-notify2
  when: ansible_facts.packages['weechat'] is defined

- name: install weechat plugin notify
  become: yes
  become_user: "{{ username }}"
  get_url:
    url: https://weechat.org/files/scripts/notify.py
    dest: ~/.weechat/python/autoload/notify.py
  when: ansible_facts.packages['weechat'] is defined
