---

- name: install golang tools
  become: yes
  ansible.builtin.apt:
    name:
    - golang

- name: golang configuration
  become: yes
  become_user: "{{ username }}"
  ansible.builtin.template:
    src: env.zsh
    dest: "~/.zsh_config/go/env.zsh"

- name: install/upgrade benchstat
  become: true
  become_user: "{{ username }}"
  command: "go install golang.org/x/perf/cmd/benchstat"
  environment:
    GO111MODULE: "on"