---

apt_releases:
  - name: focal
    mirror: http://ch.archive.ubuntu.com/ubuntu
    archive: main restricted universe multiverse
  - name: focal-security
    mirror: http://ch.archive.ubuntu.com/ubuntu
    archive: main restricted universe multiverse
  - name: focal-updates
    mirror: http://ch.archive.ubuntu.com/ubuntu
    archive: main restricted universe multiverse

grub_parameter: "mem_sleep_default=deep"

packages_extra:
  - awscli

private_node: false
username: mbrothie
