---

apt_releases:
  - name: focal
    mirror: http://ch.archive.ubuntu.com/ubuntu
    archive: main restricted universe multiverse
  - name: focal-security
    mirror: http://ch.archive.ubuntu.com/ubuntu
    archive: main restricted universe multiverse
  - name: focal-updates
    mirror: http://ch.archive.ubuntu.com/ubuntu
    archive: main restricted universe multiverse

nodejs:
  version: 14.x

private_node: false

username: djowett

github_username: djowett

device_mapper_path: /dev/mapper/vgubuntu-swap
