---

- name: configuring APT sources
  become: yes
  when: ansible_os_family == "Debian"
  template:
    src: sources.list.j2
    dest: /etc/apt/sources.list
  register: apt_source

- name: set package preferences
  become: yes
  when: ansible_os_family == "Debian"
  template:
    src: apt-preferences.j2
    dest: "/etc/apt/preferences.d/{{ item.name }}-default.pref"
  with_items: "{{ debian_releases }}"

- name: update package cache
  become: yes
  apt:
    update_cache: yes
  when: apt_source.changed

- name: installing required packages for playbook
  become: yes
  package:
    pkg: "{{ item }}"
    state: present
  with_together:
    - apt-transport-https
    - curl
    - gpg
    - python3-apt
    - python3-selinux
    - software-properties-common
    - wget
