---

- name: download poetry install script
  get_url:
    url: https://install.python-poetry.org/
    dest: /tmp/install-poetry.py
    mode: 0440

- name: install poetry
  command: "/usr/bin/python3 /tmp/install-poetry.py"
  args:
    creates: "~/.local/bin/poetry"
  environment:
    POETRY_HOME: "~/.local/"
