---

- name: install firefox
  become: true
  package:
    pkg: "firefox{% if ansible_distribution == 'Debian' %}-esr{% endif %}"

- name: check browser preferences
  command: xdg-settings get default-web-browser
  register: browser_prefs
  changed_when: false

- name: set browser preferences for firefox
  command: xdg-settings set default-web-browser firefox-esr.desktop
  when:
    - not ansible_check_mode
    - browser_prefs.stdout != "firefox-esr.desktop"
