---

- name: set package preferences for firefox quantum
  when: ansible_os_family == "Debian"
  become: yes
  copy:
    src: "1000.firefox-quantum.pref"
    dest: /etc/apt/preferences.d/1000.firefox-quantum.pref
  register: firefox_pkg_pref

- name: update package cache
  become: yes
  apt:
    update_cache: true
  when: firefox_pkg_pref.changed and ansible_os_family == "Debian"

- name: remove firefox-esr
  become: yes
  package:
    pkg: firefox-esr
    state: absent

- name: install firefox quantum
  become: yes
  package:
    pkg: firefox
    state: latest

- name: check browser preferences
  command: xdg-mime query default {{ item }}
  loop:
    - x-scheme-handler/http
    - x-scheme-handler/https
    - x-scheme-handler/ftp
  register: browser_prefs
  changed_when: browser_prefs.rc != 0

- name: set browser preferences for firefox
  command: xdg-mime default firefox.desktop {{ item.item }}
  loop: "{{ browser_prefs.results }}"
  when: item.stdout != "firefox.desktop"
