---

- name: install required packages for hibernate
  become: true
  apt:
    name:
      - pm-utils
      - hibernate
  tags: system, root, hibernate

- name: check grub setting for hibernation
  lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT=".*mem_sleep_default=deep resume={{ device_mapper_path }}'
    state: absent
  check_mode: true
  register: grub_cmdline_check
  changed_when: false
  when: device_mapper_path is defined
  tags: system, root, hibernate

- name: insert grub setting for hibernation
  become: true
  lineinfile:
    backrefs: true
    path: /etc/default/grub
    regexp: '^(GRUB_CMDLINE_LINUX_DEFAULT=".*)"$'
    line: '\1 mem_sleep_default=deep resume={{ device_mapper_path }}"'
  when: device_mapper_path is defined and grub_cmdline_check.found == 0
  notify: update grub
  tags: system, root, hibernate
