---

- name: install virtualization packages
  become: yes
  package:
    pkg: "{{ item }}"
    state: latest
  with_together:
    - cloud-image-utils
    - genisoimage
    - qemu
    - qemu-kvm
    - libvirt-clients
    - libvirt-daemon
    - libvirt-daemon-system
    - vagrant
    - vagrant-libvirt
    - virt-manager

- name: add libvirt group to {{ username }}
  become: yes
  user:
    name: "{{ username }}"
    state: present
    append: yes
    groups:
      - libvirt
  tags: user, root
