---

- name: install virtualization packages
  become: yes
  package:
    pkg: "{{ item }}"
    state: latest
  with_together:
    - cloud-image-utils
    - genisoimage
    - qemu
    - qemu-kvm
    - libvirt-clients
    - libvirt-daemon
    - vagrant
    - virt-manager
    - virtualbox
    - virtualbox-guest-additions-iso
