---

- name: install virtualization packages
  become: yes
  package:
    pkg: "{{ item }}"
    state: latest
  with_together:
    - qemu
    - qemu-kvm
    - libvirt-clients
    - libvirt-daemon
    - vagrant
    - virt-manager
