---

# Install and configure a systemd service for Dropbox
# https://www.dropbox.com/install

- name: download Dropbox
  become: yes
  when: ansible_os_family == "Debian"
  get_url:
    dest: /usr/bin/dropbox
    mode: 0755
    url: https://www.dropbox.com/download?dl=packages/dropbox.py
  register: dropbox_install

- name: configure a systemd service for Dropbox
  become: yes
  template:
    src: dropbox.service.j2
    dest: /etc/systemd/system/dropbox@.service
  register: dropbox_service

- name: service daemon reload
  become: yes
  systemd:
    daemon_reload: yes
  when: dropbox_service.changed

- name: install dropbox daemon 
  become: yes
  become_user: "{{ username }}"
  command: dropbox start -i -y
  args:
    creates: "~/.dropbox-dist"
  when: dropbox_service.changed
  register: dropbox_daemon

- name: enable systemd Dropbox service for {{ username }}
  become: yes
  systemd:
    enabled: yes
    name: "dropbox@{{ username }}.service"
    state: started
  when: dropbox_install is defined and dropbox_daemon is defined and dropbox_daemon.changed
