---

- name: install packages for work
  become: true
  package:
    pkg:
      - mumble

- name: deploy sudoers configuration
  become: true
  template:
    src: sudoers.j2
    dest: /etc/sudoers.d/zzz-custom
    validate: /usr/sbin/visudo -c %s
