---

- name: create code directory
  file:
    path: "{{ code_directory }}"
    state: directory

- name: clone projects
  git:
    clone: yes
    accept_hostkey: yes
    dest: "{{ code_directory }}/{{ item.dest }}/"
    repo: "{{ item.url }}"
    update: no
    verify_commit: no
  loop: "{{ code_projects }}"
