---

- name: change home permissions for {{ username }}
  file:
    path: "~/"
    state: directory
    mode: 0750
  tags: user

- name: create directory for ansible remote_tmp to skip warning
  file:
    path: "~/.ansible/tmp"
    state: directory
    mode: 0750
  tags: user

- name: add authorized ssh keys for {{ username }}
  authorized_key:
    key: https://github.com/marcaurele.keys
    comment: "github user key for marcaurele"
    state: present
    user: "{{ username }}"
  tags: user

- name: create directories
  file:
    path: "{{ item.path }}"
    state: directory
    mode: "{{ item.mode|default('') }}"
  loop:
    - path: "~/.config"
    - path: "~/.configi/nvim"
    - path: "~/Private"
    - path: "{{ packages_directory }}"
    - path: "~/.ssh"
      mode: '0700'
    - path: "{{ code_directory }}"
  tags: user

- name: install config dot files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode | default('0644')}}"
  loop:
    - src: curlrc.j2
      dest: "~/.curlrc"
    - src: gitconfig_adfinis.j2
      dest: "~/.gitconfig_adfinis"
    - src: gitconfig.j2
      dest: "~/.gitconfig"
    - src: gitignore_global.j2
      dest: "~/.gitignore_global"
    - src: vimrc.j2
      dest: "~/.vimrc"
    - src: nvim.j2
      dest: "~/.config/nvim/init.vim"
    - src: wgetrc.j2
      dest: "~/.wgetrc"
    - src: ssh_config.j2
      dest: "~ /.ssh/config"
    - src: gist.j2
      dest: "~/.gist"
  tags: user

- name: install extra config dot files
  file:
    state: link
    path: "{{ item.dest }}"
    src: "~/Private/{{ item.src }}"
  loop:
    - src: "config/cloudstack.ini"
      dest: "~/.cloudstack.ini"
  tags: user

- name: clone projects
  git:
    clone: yes
    accept_hostkey: yes
    dest: "{{ item.dest }}"
    repo: "{{ item.url }}"
    update: no
    verify_commit: no
  loop: "{{ code_projects }}"
  tags: user
