---

- name: change home permissions for {{ username }}
  file:
    path: "~/"
    state: directory
    mode: 0750

- name: create directory for ansible remote_tmp to skip warning
  file:
    path: "~/.ansible/tmp"
    state: directory
    mode: 0750

- name: add authorized ssh keys for {{ username }}
  authorized_key:
    key: https://github.com/marcaurele.keys
    comment: "github user key for marcaurele"
    state: present
    user: "{{ username }}"

- name: create directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "~/.config"
    - "~/Private"
    - "{{ packages_directory }}"

- name: install config dot files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode | default('0644')}}"
  loop:
    - src: curlrc.j2
      dest: "~/.curlrc"
    - src: gitconfig.j2
      dest: "~/.gitconfig"
    - src: gitignore_global.j2
      dest: "~/.gitignore_global"
    - src: wgetrc.j2
      dest: "~/.wgetrc"

- name: install extra config dot files
  file:
    state: link
    path: "{{ item.dest }}"
    src: "~/Private/{{ item.src }}"
  loop:
    - src: "config/cloudstack.ini"
      dest: "~/.cloudstack.ini"
    - src: "config/gist"
      dest: "~/.gist"
    - src: "config/runstatus"
      dest: "~/.runstatus"
    - src: "config/runstatus-ma-pp"
      dest: "~/.runstatus-ma-pp"
    # - src: "config/remmina.pref"
    #   dest: "~/.config/remmina/remmina.pref"

- name: import code related tasks
  import_tasks: code.yml
