---

- name: reboot
  shell: sleep 2 && /sbin/reboot
  poll: 0
  async: 1
  become: yes
  become_method: sudo
  ignore_errors: true

- name: wait for host to reboot
  wait_for_connection:
    sleep: 5
    delay: 30
#  delegate_to: localhost
