---

- name: install docker packages
  become: yes
  package:
    pkg: "{{ item }}"
    state: latest
  with_together:
    - docker.io
    - docker-compose

- name: add {{ username }} to docker group
  become: yes
  user:
    name: "{{ username }}"
    append: yes
    groups:
      - docker
