---

- name: create sublime config directory
  file:
    path: "~/.config/sublime-text-3/Packages/User"
    state: directory
  when: ansible_facts.packages['sublime-text'] is defined

- name: configure sublime preferences
  template:
    src: Preferences.sublime-settings.j2
    dest: ~/.config/sublime-text-3/Packages/User/Preferences.sublime-settings
  when: ansible_facts.packages['sublime-text'] is defined
