---

- name: install python packages
  become: yes
  package:
    pkg: "{{ item }}"
  with_together:
    - python3
    - python3-pip

- name: install some python mackages through pip
  become: yes
  pip:
    name:
      - pipenv
      - virtualenv
    state: latest
