---

- name: install python packages
  become: yes
  package:
    pkg: "{{ item }}"
    state: latest
  with_together:
    - python
    - python-pip
    - python3
    - python3-pip

- name: install global python modules
  pip:
    name: virtualenv
    state: present
