---

- name: install python packages
  become: yes
  package:
    pkg: "{{ item }}"
    state: latest
  with_together:
    - python3
    - python3-pip
    - python3-venv
    - python3-virtualenv
    - python3-virtualenvwrapper
