---

- name: install python packages
  become: yes
  package:
    pkg: "{{ item }}"
  with_together:
    - pipenv
    - python3
    - python3-pip
    - python3-virtualenv
    - python3-virtualenvwrapper
