---

- name: add repository GPG key for FortiClient (VPN)
  become: true
  apt_key:
    url: https://repo.fortinet.com/repo/7.0/ubuntu/DEB-GPG-KEY

- name: add repository for FortiClient (VPN)
  become: true
  apt_repository:
    repo: deb [arch=amd64] https://repo.fortinet.com/repo/7.0/ubuntu/ /bionic multiverse

- name: install FortiClient (VPN)
  become: true
  apt:
    pkg: forticlient
    state: latest
