---
packages_directory: "~/soft"
code_directory: "~/code"
pyenv:
  versions:
    - 2.7.15
    - 3.5.6
    - 3.6.7
    - 3.7.1
  default: 3.6.7
pipsi_tools:
  - name: cs
  - name: flake8
    extra: flake8-import-order, flake8-bugbear
  - name: pip-tools
  - name: sphinx
    extra: sphinx-rtd-theme, recommonmark
  - name: runstatus-cli
  - name: black
  - name: ansible
    extra: passlib, jmespath, cs
  - name: python-gist

code_projects: '{{ vault_code_projects }}'
