---

- name: include distribution APT configuration
  include_tasks: "{{ ansible_distribution | lower }}.yml"

- name: install required packages for playbook
  become: yes
  apt:
    name:
      - apt-transport-https
      - curl
      - gpg
      - python3-apt
      - software-properties-common
      - wget
  tags: system, root
